language: python
python:
        - "3.5"
        - "3.4"
        - "2.7"

env:
  - C_INCLUDE_PATH=$HOME/libraries/include

cache:
  directories:
  - $HOME/libraries

before_install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - deactivate  # Deactivate virtualenv
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - sudo apt-get install liblapack-dev libblas-dev
install:
  - conda create -q -y -n fidimag-test python=$TRAVIS_PYTHON_VERSION cython matplotlib pytest scipy pytest-cov gcc cmake psutil
  - source activate fidimag-test
  - pip install pyvtk six nbval ipywidgets

before_script:
        - bash ${TRAVIS_BUILD_DIR}/bin/travis-libs-helper.sh
        - conda list
        - make build
        - export PYTHONPATH="$TRAVIS_BUILD_DIR:$PYTHONPATH"
        - export LD_LIBRARY_PATH="$HOME/libraries:$LD_LIBRARY_PATH"
        - export LD_RUN_PATH="$HOME/libraries:$LD_RUN_PATH"
        - export OMP_NUM_THREADS=1
        - export MPLBACKEND=Agg
        # Tells matplotlib (?) to use PyQt class v2 APIs (I think)
        - export QT_API=pyqt

# command to run tests
script:
  - make test-without-run-oommf
  - make test-ipynb


notifications:
  email:
    on_failure: always

after_success:
  - bash <(curl -s https://codecov.io/bash)
